### ISSUE TITLE
namespace of composer package is wrong

### ISSUE THREAD

**Issue by hgiesenow** [phpstan/phpstan-symfony#1]
At packagist.org the package `phpstan/phpstan-symfony` is not available. For the installation you must type `composer require --dev lookyman/phpstan-symfony` instead and also include the config from different namespace `vendor/lookyman/phpstan-symfony/extension.neon`.

**Comment by lookyman** [comment]
That is because this package is not yet on Packagist. It will be available with the next PHPStan release. Until that time, you should use the https://github.com/lookyman/phpstan-symfony package.
