### ISSUE TITLE
composer.json version requirement for nikic/php-parser possibly too restrictive

### ISSUE THREAD

**Issue by dohpaz42** [phpstan/phpstan-symfony#10]
I recently ran into a [version conflict](https://github.com/phpDocumentor/Reflection/issues/129) between this package and [`phpDocumentor/Reflection`](https://github.com/phpDocumentor/Reflection) with respect to [`nikic/php-parser`](https://github.com/nikic/PHP-Parser).

This project's package requires `^4.0`, while the aforementioned package requires either `^1.0` or `^3.0` - depending on how bleeding edge you want to be. 

The problem with this is that if `nikic/php-parser` releases a major version faster than your library, and another package depends on that newer version, there will be a version conflict disallowing said package and this package from being installed. This in fact is the case for trying to install this package along side `phpDocumentor/Reflection` (which is depended on by `ramsey/jenkins-php`). 

My suggestion, as a library, would be to use a less restrictive version constraint of `>=4.0` so that your library can still take advantage of the minimum requirements while not conflicting with newer packages/libraries depending on newer versions.

Thank you.

**Comment by ondrejmirtes** [comment]
Hi, this is not possible, the new PHP parser is quite different and it's not possible to support old and new version at the same time.

**Comment by ondrejmirtes** [comment]
Your solution is to install PHPStan separately with a different composer.json (in a subdirectory perhaps) or use something like Docker for this (https://github.com/phpstan/docker-image).

**Comment by dohpaz42** [comment]
@ondrejmirtes you misunderstand, I am by far not asking for support of `^1.0`. Please re-read this key statement:

> My suggestion, as a library, would be to use a **less restrictive version constraint of >=4.0** so that your library can still take advantage of the minimum requirements while not conflicting with newer packages/libraries depending on newer versions.

**Comment by ondrejmirtes** [comment]
I don't see how having "nikic/php-parser": ">=4.0" instead of `"nikic/php-parser": "^4.0"` would help?

**Comment by ondrejmirtes** [comment]
It would be too dangerous to proclaim support for php-parser 5.x when there will be BC breaks and work involved to really support it.

**Comment by dohpaz42** [comment]
@ondrejmirtes if `package/xyz` requires `nikic/php-parser: "^5.0", then I would not be able to use `phpstan/phpstan-symfony` because this package's constraint says it's restricted to just the `4.0` branch. If, however, this package said `>=4.0`, then everybody would be happy.

**Comment by ondrejmirtes** [comment]
It would be too dangerous to proclaim support for php-parser 5.x when there will be BC breaks and work involved to really support it. 😊

**Comment by dohpaz42** [comment]
@ondrejmirtes Thank you for the pointer about different directories; it caused me to stumble on [support for environment variables by composer](https://getcomposer.org/doc/03-cli.md#environment-variables), which let's me hack around this ugly limitation.

I will leave you with this plea: please strongly consider opening up version constraints (as much as future versions will allow you, re: backward-compatibility). [Short-sightedness leads to doors being slammed in developer's faces](https://github.com/composer/composer/issues/2167).

Thank you! :)

**Comment by ondrejmirtes** [comment]
I have to always consider the maintenance burden when opening up the constraints but maybe the next major PHP-Parser version won't contain as many changes 😊 After all, I supported 2.x alongside 3.x for a long time 😊
