### ISSUE TITLE
Suggestion: Warm up Symfony's cache to prevent error "Container ... does not exist"

### ISSUE THREAD

**Issue by ThomasLandauer** [phpstan/phpstan-symfony#102]
When I run PHPStan after deleting my `var/cache/dev` directory, I'm getting this error:
> Container .../var/cache/dev/srcApp_KernelDevDebugContainer.xml does not exist

So I need to open the app in "dev" environment first, before I can run PHPStan. So I'm suggesting to automatically try to warm up the cache (or initialize the app) by PHPStan.

**Comment by ondrejmirtes** [comment]
Hi, you should run PHPStan by putting in your `Makefile` or Composer scripts warming up the container first and only then running analyse. This should be solved outside of PHPStan like that.
