### ISSUE TITLE
GitHub shows 0.11.6 as latest while there are more releases

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-symfony#104]
https://github.com/phpstan/phpstan-symfony/releases

<img width="487" alt="Screenshot 2020-10-20 at 10 46 07@2x" src="https://user-images.githubusercontent.com/104180/96562807-7b352280-12c1-11eb-9e93-2040e6d7a9fb.png">

**Comment by ruudk** [comment]
Seems to be something weird with Github indeed. 

https://github.community/t/why-last-release-is-not-marked-as-latest-release/421/5

Could it be that the 0.11.6 release was created with the GitHub web interface? And the later tags where just done via git push?

**Comment by ondrejmirtes** [comment]
In 0.11.x series I had been creating GitHub releases, from 0.12 onwards I'm just doing tags.
