### ISSUE TITLE
Support for ContainerInterface::getParameter return type

### ISSUE THREAD

**Issue by garak** [phpstan/phpstan-symfony#127]
Problem: [ContainerInterface](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/DependencyInjection/ContainerInterface.php) returns `array|bool|float|int|string|null` as value.

This is causing false positive in phpstan analysis, when you know that returned value has a specific type and you try to use it. For example, if you retrieve a string using `$container->getParameter('my_parameter')`, you currently can't do a concatenation, since phpstan is complaining about `Binary operation "." [...] results in an error`

It would be nice if the plugin could be able to retrieve actual type from container and override the return type of `getParameter` method.

**Comment by ondrejmirtes** [comment]
Hi, there's already an extension for retrieving services out of the container here https://github.com/phpstan/phpstan-symfony/blob/master/src/Type/Symfony/ServiceDynamicReturnTypeExtension.php, feel free to get inspired and implement it for parameters too.

**Comment by FerJEP** [comment]
@garak Hi, Did you work around this issue?

**Comment by garak** [comment]
> @garak Hi, Did you work around this issue?

not yet

**Comment by Kocal** [comment]
Hi guys!

I'm actually working on it since I faced the issue some days ago.

I copy/pasted services-related code but for parameters and was able to build a `DefaultParameterMap` given the XML Symfony container.
Now I just need to create a phpstan extension and I will be ready to open a PR.

**Comment by ondrejmirtes** [comment]
Implemented by https://github.com/phpstan/phpstan-symfony/pull/152, thanks @Kocal!

**Comment by ondrejmirtes** [comment]
Enjoy it in phpstan-symfony 0.12.29 :)
