### ISSUE TITLE
no container .xml written by Symfony anymore. Problem or not?

### ISSUE THREAD

**Issue by jorismak** [phpstan/phpstan-symfony#128]
Not really 'an issue', more a question.

I had a working phpstan setup for a Symfony 5.2 project. The phpstan.neon contained something like this:
```
parameters:    
    symfony:
        container_xml_path: '%rootDir%/../../../var/cache/dev/App_KernelDevDebugContainer.xml'
```

But now - after installing another symfony component I believe, with a `composer require translator` the Symfony cache:clear doesn't write any xml file at all in the var/cache/dev directory.

The project is working fine :). It seemed the Symfony container switched to writing files as .php and .php.meta instead of .xml or something like that?

If I remove the 'container_xml_path' line `phpstan analyze -l6` seems to work fine as well. I'm not sure if the symfony-extension is working now or not.

Is the 'container_xml_path' indeed not needed anymore, or does something more require changes?

Kind regards.

**Comment by mhujer** [comment]
@jorismak which Symfony version do you use? There was an issue in 5.2.0 which caused exactly this: https://github.com/symfony/symfony/issues/39240

**Comment by ondrejmirtes** [comment]
Yes, it's mentioned here https://github.com/phpstan/phpstan-symfony/issues/112.

**Comment by jorismak** [comment]
I guess I didn't searh hard enough.

Still weird that the problem 'suddenly popped up'. The project was started at 5.2.x and worked fine, and now suddenly didn't work without any explicit `composer update`s.

Maybe something sneaked through in a coworker's PR  or something.. 🤷‍♂️ .

I'll use `lint:container` as a workaround if I get it again... upgrading seems better :)
