### ISSUE TITLE
services_test.yml is not considered in test context

### ISSUE THREAD

**Issue by nCrazed** [phpstan/phpstan-symfony#13]
I have a `RealImplementation` with potentially expensive calls that is registered for a `ServiceInterface` in `services.yml` file. This is overwritten for tests via `services_test.yml` to instead use a `MockImplentation`. 

There's also a sanity check in relevant tests to ensure that the correct version is being used:

```php
 $service = $container->get(ServiceInterface::class);
 \assert($service instanceof MockImplementation);
```

This assertion triggers the following error:

```
Call to function assert() with false will always evaluate to false.                                                                                  
Instanceof between RealImplementation and MockImplementation will always evaluate to false.
```

This can be worked around by manually widening the type of the variable like so:

```php
/** @var ServiceInterface $service **/
 $service = $container->get(ServiceInterface::class);
 \assert($service instanceof MockImplementation);
```

**Comment by lookyman** [comment]
Hi, sorry for the delay. Do you use test container in your `phpstan.neon`? It should look something like this:

```
parameters:
	symfony:
		container_xml_path: %rootDir%/../../../var/cache/test/appTestDebugProjectContainer.xml
```

You can use a separate `phpstan.test.neon` for tests which just includes the normal one and overwrites the container definition.

**Comment by nCrazed** [comment]
No, I was using the same configuration for the whole codebase.

Having separate config for the test files makes sense, thanks.
