### ISSUE TITLE
[Command] Required argument can not return `null`

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-symfony#133]
if you add an argument to your command which is required:

`$this->addArgument('name', InputArgument::REQUIRED)`

then

`$name = $input->getArgument('name');`

could not return `null`. 

This is also the case for default values:
`$this->addArgument('ids', InputArgument::IS_ARRAY | InputArgument::OPTIONAL, [])`

**Comment by ondrejmirtes** [comment]
Please send a PR that fixes it here: https://github.com/phpstan/phpstan-symfony/blob/master/src/Type/Symfony/InputInterfaceGetArgumentDynamicReturnTypeExtension.php

**Comment by mitelg** [comment]
will try that, once I have the time :smiley: :+1:

**Comment by mitelg** [comment]
fixed because of https://github.com/phpstan/phpstan-symfony/issues/134#issuecomment-780453267
