### ISSUE TITLE
[Command] option with config `InputOption::VALUE_NONE` is always a boolean

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-symfony#134]
an option like this `$this->addOption('keep-user-data', null, InputOption::VALUE_NONE, 'Keep user data of the plugin');` is always `true` or `false` depending on whether the option is provided or not.

**Comment by ondrejmirtes** [comment]
Hi, just to be sure, do you provide your own `console_application_loader`? https://github.com/phpstan/phpstan-symfony#console-command-analysis

**Comment by mitelg** [comment]
oh wow, shame on me :facepalm:  Didn't see this config. this resolves my two issues :sweat_smile:
