### ISSUE TITLE
Cannot declare interface PhpParser\NodeVisitor

### ISSUE THREAD

**Issue by TamasSzigeti** [phpstan/phpstan-symfony#138]
This was already reported in https://github.com/phpstan/phpstan/issues/4067 but a reproducer wasn't provided so I created one:
Repo: https://github.com/lingoda/stan_redeclare_repro
Failing stan: https://github.com/lingoda/stan_redeclare_repro/runs/2005010757

As suggested in the original report, it is somehow caused by `$input->getOption()` in the Command, in combination with the installed `jms/translation-bundle` that depends on `nikic/php-parser`.

Weirdly, the issue doesn't reproduce locally, only in GitHub CI

Thank you in advance for looking into it.

**Comment by ondrejmirtes** [comment]
See the note at the end of the README: https://github.com/phpstan/phpstan-symfony#console-command-analysis that starts with "You may then encounter an error with PhpParser:"...

**Comment by TamasSzigeti** [comment]
Oops sorry, haven't seen that
