### ISSUE TITLE
console-application.php for Symfony 5.1?

### ISSUE THREAD

**Issue by ThomasLandauer** [phpstan/phpstan-symfony#141]
Since `config/bootstrap.php` doesn't exist anymore in Symfony 5.1 (see https://github.com/symfony/symfony-docs/issues/13759), the example `console-application.php` at https://github.com/phpstan/phpstan-symfony#console-command-analysis doesn't work anymore.

I did it quick and dirty like so, but what's the recommended way (to also be shown in README)?:
```php
use App\Kernel;
$kernel = new Kernel('dev', false);
return new \Symfony\Bundle\FrameworkBundle\Console\Application($kernel);
```

`object-manager.php` at https://github.com/phpstan/phpstan-doctrine#configuration is also affected.

**Comment by mhujer** [comment]
My `console-boostrap.php` looks like this:

```php
<?php declare(strict_types = 1);

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__) . '/../vendor/autoload.php';

(new Dotenv())->bootEnv(dirname(__DIR__) . '/../.env');

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
return new Application($kernel);
```

And `doctrine-orm-bootstrap.php`:

```php
<?php declare(strict_types = 1);

use App\Kernel;
use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__) . '/../vendor/autoload.php';

(new Dotenv())->bootEnv(dirname(__DIR__) . '/../.env');

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();
return $kernel->getContainer()->get('doctrine')->getManager();
```

**Comment by ondrejmirtes** [comment]
@mhujer Can you please send a PR here and in phpstan-doctrine that updates the instructions in the README? I hope the new way is also backward compatible with older Symfony/Doctrine versions. Thank you.

**Comment by ThomasLandauer** [comment]
For Symfony 4.4 they're recommending to have a `bootstrap.php`:
https://symfony.com/doc/4.4/configuration/dot-env-changes.html#updating-my-application
vs.
https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application
