### ISSUE TITLE
MutableAclProviderInterface stub is not working

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-symfony#149]
The following PR is failing:
https://github.com/sonata-project/SonataAdminBundle/pull/7095

The interesting code is the following
```
    /**
     * @var MutableAclProviderInterface
     */
    protected $aclProvider;

    public function getObjectAcl(ObjectIdentityInterface $objectIdentity)
    {
        try {
            return $this->aclProvider->findAcl($objectIdentity);
        } catch (AclNotFoundException $e) {
            return null;
        }
    }
```
which is throwing an error
```
Method                                                                 
         Sonata\AdminBundle\Security\Handler\AclSecurityHandler::getObjectAcl(  
         ) should return                                                        
         Symfony\Component\Security\Acl\Model\MutableAclInterface|null but      
         returns Symfony\Component\Security\Acl\Model\AclInterface.
```

the stub of MutableAclProviderInterface is supposed to be
```
    /**
     * @phpstan-param array<SecurityIdentityInterface> $sids
     * @phpstan-return MutableAclInterface
     */
    public function findAcl(ObjectIdentityInterface $oid, array $sids = []);
```

**Comment by ondrejmirtes** [comment]
The method `findAcl` is not defined on MutableAclProviderInterface but on AclProviderInterface. Please update the stub and look for other similar issues. Thanks.

**Comment by VincentLanglet** [comment]
You mean this way ?
```
    /**
     * @method MutableAclInterface findAcl(ObjectIdentityInterface $oid, array $sids = [])
     * @method \SplObjectStorage<ObjectIdentityInterface, MutableAclInterface> findAcls(array $oids, array $sids = [])
     */
```

**Comment by ondrejmirtes** [comment]
No. Just move the `findAcl()` method to the `AclProviderInterface` stub.

**Comment by VincentLanglet** [comment]
`findAcl` is already in the AclProviderInterface stub: https://github.com/phpstan/phpstan-symfony/pull/148/files#diff-33f2d256bf885a2590268760c701c32e54da27bd8b74399853b0d69bc668fad8

I wanted to override the return type of these method to use `MutableAclInterface` instead of `AclInterface`.

The first time I made this stub I tried with generics, but you told me:
> And BTW you don't have to solve this with generics, I'm not sure it makes sense here. You can simply override the method in the child MutableAclProviderInterface and say it returns MutableAclInterface.

**Comment by ondrejmirtes** [comment]
In that case it's something that needs to be supported in PHPStan core. I wasn't aware it's not going to work like that.

**Comment by ondrejmirtes** [comment]
Nope, that's the wrong solution.

**Comment by VincentLanglet** [comment]
Closing because of https://github.com/phpstan/phpstan-symfony/releases/tag/0.12.39
