### ISSUE TITLE
Container has check throw condition is always true

### ISSUE THREAD

**Issue by alexander-schranz** [phpstan/phpstan-symfony#15]
```php
if (!$container->has('doctrine.orm.entity_manager')) {
    throw new \InvalidArgumentException('Configure your entity manager correctly');
}
```

In my bundle I have a check for `has` service the phpstan throw the following error: `If condition is always true.` or `Negated boolean is always false.` because I think the service exist in my current configured container file. But this check is needed as somebody which don't have the other library imported or configured it different. 

I think `has` should always be possible to be `true` or `false`.

**Comment by lookyman** [comment]
Just so I understand it correctly, the bundle is not part of your application, but is a separate package that you install into it?

**Comment by alexander-schranz** [comment]
@lookyman the project using phpstan is a bundle and has check is used here to output a false configuration of the application use this bundle.

Another better usecase is when you are developing a bundle which has `optional` dependencies e.g.:

```php
if (!$container->has('ffmpeg')) {
      // register ffmpeg related services
}
```

so the optional dependency is in the test container of the bundle but could not be there when somebody use the bundle so the `has` check is needed.

**Comment by lookyman** [comment]
Right. That is a use case I haven't really considered. I don't want to just disable checking the `has` methods, because they can provide useful information about the code. What would you recommend in this case? I see two possibilities. Either add a config parameter to disable the checking altogether, or perhaps a blacklist for service names that we don't want to check. What do you think?

**Comment by alexander-schranz** [comment]
@lookyman list of optional services sounds good for me. but it should only change the behaviour of `has` would `get` let it be as it is.

**Comment by lookyman** [comment]
Yes, of course, `get` methods will remain unchanged. Thank you, I will look into that.

**Comment by alexander-schranz** [comment]
Not sure if relevant there is in symfony a feature called ServiceSubscriber which can give you a container with only specified services: https://symfony.com/doc/current/service_container/service_subscribers_locators.html.

**Comment by COil** [comment]
Having the same issue.

**Comment by alexander-schranz** [comment]
@COil oh yeah thats also a use case which could also happen in a project not in a bundle. What is your opinion how we should fix the problem? I think we have 3 options:

 - A: let him define which services are optionals
 - B: let it configure to check if `has` ends up in a always check
 - C: has can always be true and false

**Comment by lookyman** [comment]
Fixed in 0.10.2. Check out the readme.

**Comment by alexander-schranz** [comment]
@lookyman thank you!

**Comment by COil** [comment]
It's ok thank you. :)
