### ISSUE TITLE
Parameter return types introduces will evaluate always false

### ISSUE THREAD

**Issue by shyim** [phpstan/phpstan-symfony#157]
We have an our project a Container Parameter `shopware.release.version_text` which contains version texts like RC etc.

In Git Installation it uses always the default `___VERSION_TEXT___`. With the new Parameter understanding, PHPStan fails now with 
`Strict comparison using !== between '___VERSION_TEXT___' and '___VERSION_TEXT___' will always evaluate to false. `

Code-Snippet: 
```php
$shopwareVersionText = $this->container->getParameter('shopware.release.version_text');
return $shopwareVersionText !== '___VERSION_TEXT___';
```

How can we avoid such errors? The variable is only same on Git and not on tagged release. Does it maybe make more sense to have an config option to return the right type but not the value? 🤔

**Comment by ondrejmirtes** [comment]
Already fixed in phpstan-symfony 0.12.30: https://github.com/phpstan/phpstan-symfony/issues/153 + https://github.com/phpstan/phpstan-symfony/pull/156
