### ISSUE TITLE
Support custom Symfony Validation Constraint

### ISSUE THREAD

**Issue by Kocal** [phpstan/phpstan-symfony#16]
Hello, I'm encountering an issue with custom Validation Constraint.

PhpStan returns me this error:
```
 ------ ----------------------------------------------------------------------------------- 
  Line   common/Bundle/Common/CoreBundle/Validator/Constraints/IsStringValidator.php        
 ------ ----------------------------------------------------------------------------------- 
  21     Access to an undefined property Symfony\Component\Validator\Constraint::$message.  
 ------ ----------------------------------------------------------------------------------- 
```

This is my code (just an example, not for production :smile:) :

```php
<?php
// packages/common/Bundle/Common/CoreBundle/Validator/Constraints/IsStringValidator.php

declare(strict_types=1);

namespace Yprox\Bundle\Common\CoreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class IsStringValidator extends ConstraintValidator
{
    /**
     * {@inheritdoc}
     */
    public function validate($value, Constraint $constraint)
    {
        if (null === $value || is_string($value)) {
            return true;
        }

        $this->context->addViolation($constraint->message);

        return false;
    }
}
```

```php
<?php
// packages/common/Bundle/Common/CoreBundle/Validator/Constraints/IsString.php

declare(strict_types=1);

namespace Yprox\Bundle\Common\CoreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class IsString extends Constraint
{
    public $message = 'Value must be a string';
}
```

And this is normal, because there is no property `$message` on abstrac class `Symfony\Component\Validator\Constraint`.

---

I tried to update my code to this:
```php
/**
 * {@inheritdoc}
 */
public function validate($value, IsString $constraint)
```

but I can't because the declaration is not compatible with `ConstraintValidatorInterface::validate($value, Constraint $constraint)`.

So I tried with a PHPDoc like this:
```php
/**
 * {@inheritdoc}
 * @param IsString $constraint
 */
public function validate($value, Constraint $constraint)
```

but I still have the same error from PhpStan.

---

Is there any workaround for that? Should I ignore this error by configuring PhpStan?

Maybe PhpStan can automatically call [`Constraint#validatedBy()`](https://symfony.com/doc/current/validation/custom_constraint.html#creating-the-validator-itself)? I'm not sure about that :confused: ...

Thank you! :slightly_smiling_face:

**Comment by lookyman** [comment]
For now, just ignore the error in PHPStan's config. But I will look into what can be done about it. Haven't really worked with the validation component before, so it may take a while..

**Comment by Kocal** [comment]
Okay thanks :+1:

**Comment by lookyman** [comment]
Also, maybe you could probably just add something like `assert($constraint instanceof IsString);` into the `IsStringValidator::validate()` method..

**Comment by alcaeus** [comment]
Pretty much every Symfony constraint does exactly that: https://github.com/symfony/symfony/blob/2bfcaeb31ff3b878734b0951851d25abf2b3321e/src/Symfony/Component/Validator/Constraints/NotNullValidator.php#L28. There should not be any magic involved with this: I could easily create a `FooConstraint` that returns `YourValidator::class` in its `validatedBy` method, and all of a sudden `YourValidator::validate` would run into a fatal error because it receives a constraint class it doesn't expect or understand. In this case, you want to make sure you're given the correct type instead of assuming some magic to do so.

**Comment by Kocal** [comment]
Oh, I didn't know Symfony check for `Constraint` instance.
Well, I will do the same, thanks you guys!

**Comment by ismail1432** [comment]
Thanks @alcaeus  :+1:

**Comment by hmartin** [comment]
`
<?php
// packages/common/Bundle/Common/CoreBundle/Validator/Constraints/IsStringValidator.php

declare(strict_types=1);

namespace Yprox\Bundle\Common\CoreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class IsStringValidator extends ConstraintValidator
{
    /**
     * {@inheritdoc}
     */
    public function validate($value, Constraint $constraint)
    {
        if (!$constraint instanceof IsString) {
            throw new UnexpectedTypeException($constraint, IsString::class);
        }
        if (null === $value || is_string($value)) {
            return true;
        }

        $this->context->addViolation($constraint->message);

        return false;
    }
}
`
As @lookyman says, it passess (phpstan level 8)...
