### ISSUE TITLE
Unexpected option 'parameters -> exceptions'

### ISSUE THREAD

**Issue by konradkozaczenko** [phpstan/phpstan-symfony#161]
Hi, I am using phpstan v0.12.86 and phpstan-symfony v0.12.33. When I try tu run phpstan analyse:
```
Invalid configuration:
Unexpected option 'parameters › exceptions'.
```
When I removed from phpstan-symfony/extension.neon lines
```	
exceptions:
	uncheckedExceptionClasses:
		- 'Symfony\Component\Console\Exception\InvalidArgumentException'
```

everything is ok

**Comment by ondrejmirtes** [comment]
I don't think you're running PHPStan 0.12.86. Verify that by running `vendor/bin/phpstan --version`.
