### ISSUE TITLE
FormView->getIterator is returning an ArrayIterator

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-symfony#164]
Hi @ondrejmirtes, I have an issue with the following code
```
final class FormViewIterator implements \RecursiveIterator
{
    /**
     * @var \ArrayIterator<string, FormView>
     */
    private $iterator;

    public function __construct(FormView $formView)
    {
        $this->iterator = $formView->getIterator();
    }
```
returning the error:
```
Property Sonata\AdminBundle\Util\FormViewIterator::$iterator (ArrayIterator<string, Symfony\Component\Form\FormView>) does not accept Traversable<string, Symfony\Component\Form\FormView>.
```
but our code rely on the fact it's an ArrayIterator.

The stub is here: https://github.com/phpstan/phpstan-symfony/blob/master/stubs/Symfony/Component/Form/FormView.stub
But shouldn't Symfony phpdoc be used ? 
```
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/FormView.php#L151
```

**Comment by ondrejmirtes** [comment]
I guess it's complicated. Feel free to add the getIterator stub with PHPDoc here.

**Comment by VincentLanglet** [comment]
> Feel free to add the getIterator stub with PHPDoc here.

Sure https://github.com/phpstan/phpstan-symfony/pull/168 should fix it, isn't it ?
