### ISSUE TITLE
Analysis of Symfony command without providing a console loader

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-symfony#165]
This would be nice to have something similar to https://github.com/psalm/psalm-plugin-symfony/blob/8122414959e56601586853040aa13dac60ad0870/src/Handler/ConsoleHandler.php in order to get the correct type from the call 
```
$input->getArgument('foo'),
```
by using directly the declaration
```
->addArgument('foo', InputArgument::REQUIRED)
```

This would be useful when there is no kernel in the bundle, only command and maker.

**Comment by ondrejmirtes** [comment]
I don't see a reason to do that. PHPStan way works better and 100 % of the time.

Kernel isn't a requirement, all you need is a file that does:

```php
$app = new Application();
$app->add(new MyCommand());

return $app;
```
