### ISSUE TITLE
FormInterface::getErrors could have a dynamic return extension

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-symfony#166]
Currently, its return type is a FormErrorIterator with inside
`Symfony\Component\Form\FormError|Symfony\Component\Form\FormErrorIterator`

The phpdoc is 
```
/**
     * Returns the errors of this form.
     *
     * @param bool $deep    Whether to include errors of child forms as well
     * @param bool $flatten Whether to flatten the list of errors in case
     *                      $deep is set to true
     *
     * @return FormErrorIterator An iterator over the {@link FormError}
     *                           instances that where added to this form
     */
    public function getErrors(bool $deep = false, bool $flatten = true);
```

So I would say it's always an iterator on `Symfony\Component\Form\FormError`, except if the parameter `true, false` are provided.

**Comment by mitelg** [comment]
I also just stumbled upon that and would love to see that, too :blush: :+1:

**Comment by VincentLanglet** [comment]
> I also just stumbled upon that and would love to see that, too 😊 👍

This shouldn't be too hard to implement ; do you want to make a try ? @mitelg

**Comment by mitelg** [comment]
If you can hint me where to start and maybe even an example where I can take things from, I would like to give it a try :grin:

**Comment by VincentLanglet** [comment]
https://github.com/phpstan/phpstan-symfony/blob/master/src/Type/Symfony/RequestDynamicReturnTypeExtension.php
can be a good example.

You'll have to implement your own logic inside getTypeFromMethodCall, but check like `(new ConstantBooleanType(true))->isSuperTypeOf($argType)` will be the same

**Comment by mitelg** [comment]
I tried to start and currently I am stuck at defining the new return type. I think i need to return `new ObjectType(FormErrorIterator::class)` in the `getTypeFromMethodCall` but how do I define the generic type?

**Comment by VincentLanglet** [comment]
You have generics here: https://github.com/phpstan/phpstan-src/tree/master/src/Type/Generic

**Comment by ondrejmirtes** [comment]
Documentation is here: https://phpstan.org/developing-extensions/dynamic-return-type-extensions

**Comment by ondrejmirtes** [comment]
Fixed by https://github.com/phpstan/phpstan-symfony/pull/228
