### ISSUE TITLE
Command addOption fails with boolean default

### ISSUE THREAD

**Issue by codeTom** [phpstan/phpstan-symfony#172]
Using a `bool` as default value for a command option with `InputOption::VALUE_REQUIRED` fails with `Parameter #5 $default of method Symfony\Component\Console\Command\Command::addOption() expects int|string|null, bool given.`.

The phpdoc for this function had
`@param string|string[]|int|bool|null $default     The default value (must be null for InputOption::VALUE_NONE)` until recently and current symfony versions seem to be using `string|string[]|bool|null` (i.e. removed `int`).
so this should be valid, but the relevant rule only includes `int|string|null`:
https://github.com/phpstan/phpstan-symfony/blob/0cd5b0d7666294c2a983aa276bb2d7fa125d0ae4/src/Rules/Symfony/InvalidOptionDefaultValueRule.php#L73 

Can bool be added to this rule? Alternatively, if there is a reason why bool was not included in that type could the error message be changed to explain it better as seeing this error which does not match the relevant phpdoc is very confusing.

**Comment by ondrejmirtes** [comment]
Yeah, feel free to send a PR, thanks :)

**Comment by codeTom** [comment]
PR for adding BooleanType is above, what do you think about removing int? Looks like all currently supported versions of symfony (4.4, 5.2+) have removed `int` from the `$default` types ( https://github.com/symfony/symfony/commit/bbf786c3dbe660dde6c38620ce5f86fc361f47f6 ), I can add https://github.com/codeTom/phpstan-symfony/commit/7d82bb6aa4f6585ed3f72fdc9bb0e7fd8b11f5cd to the PR to remove it from the rule (at the risk of confusing people on unsupported versions of symfony). Thanks.
