### ISSUE TITLE
Plugin could not determine class-string parameter

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-symfony#175]
Hey there :blush: :wave: 

Is it possible to determine class-string parameters for the `Symfony\Component\DependencyInjection\ContainerInterface::get` method?
Have a look at this example: https://phpstan.org/r/3106799a-1bca-447f-92b0-defadcd3dd60

as `$className` parameter I get class names of classes which implement the `TestInterface`. Is it somehow possible to resolve this error?

**Comment by ondrejmirtes** [comment]
Hi, sure, with this stub file: https://phpstan.org/r/7d90e24c-1980-4d1f-a9cb-9353a80407cb (https://phpstan.org/user-guide/stub-files)

I don't think that generally the Symfony DIC works like that, so it's a special case just for your codebase, right?

**Comment by mitelg** [comment]
:thinking: 

but if I call the get method with a FQCN PHPStan has no problem to detect the right class. so if I define that the class is of type `TestInterface` before, why cannot PHPStan detect that a class with this interface is returned?
Or do I miss something here? :slightly_smiling_face: 
Can you show me, where the container logic is located?

**Comment by ondrejmirtes** [comment]
Do you mean that with the actual extension, these two results would be different? https://phpstan.org/r/c52d337d-3d48-4338-8644-fb840b37d69b

What the extension currently does is that when given a service name `'test'`, it will look up the actual service type in the container, and resolve the returned type to that. Is it a common practice in Symfony to name the DI services the same way as classes?

The logic is here: https://github.com/phpstan/phpstan-symfony/blob/master/src/Type/Symfony/ServiceDynamicReturnTypeExtension.php

**Comment by mitelg** [comment]
I don't know if it is best practice, but it is also used a lot in the examples in the Symfony docs like this:
```
        <service id="App\Service\FooBar">
            <argument type="service" id="App\Service\Foo"/>
        </service>
```
We are also using this syntax in 99% of the cases. With this the class attribute is not required. 

Until now, I thought this is like the extension was working :grin: 
We give a FQCN into the get method and PHPStan knows that the return object is of type of that given class :slightly_smiling_face:
But if I see that right, PHPStan just searches for the given ID in the container and returns the object type.

The problem in my case is, that there is no service in the container which has actually the ID `TestInterface`.
But maybe, it is possible to assert, that the returned object is of the given type, if it is a FQCN? :thinking:

**Comment by ondrejmirtes** [comment]
> The problem in my case is, that there is no service in the container which has actually the ID TestInterface

So how does Symfony DIC decide what object to return in that case? Can you point me to a piece of code in Symfony that does that?

**Comment by mitelg** [comment]
~Maybe again I wanted to do things, which do not make sense~ :smiley: 
~Anyway I try to explain~ :slightly_smiling_face:

I thought about that again, and I think it does not makes sense, what I had in mind :grin: 

thanks again for the discussion and rubber ducking :slightly_smiling_face: 
I hope, I did not steal to much much time from you :see_no_evil:
