### ISSUE TITLE
Support for Symfony\Config\* classes

### ISSUE THREAD

**Issue by faizanakram99** [phpstan/phpstan-symfony#182]
Symfony now supports config builder classes https://symfony.com/blog/new-in-symfony-5-3-config-builder-classes, added in this PR https://github.com/symfony/symfony/pull/40600

PHPStan does not recognise those classes.

![image](https://user-images.githubusercontent.com/10880992/124129295-478ad900-da9b-11eb-842f-53bc3b40c96f.png)

Can we support them ?

**Comment by ondrejmirtes** [comment]
Hi, what's special about them? You can follow the usual Discovering Symbols guide to let PHPStan know about unknown classes: https://phpstan.org/user-guide/discovering-symbols

**Comment by faizanakram99** [comment]
Thanks, `scanDirectories` works.

These classes are generated and are dumped into `%kernel.build_dir%/Symfony` directory.
