### ISSUE TITLE
InputInterface::getOption return type not properly inferred if called through a helper method

### ISSUE THREAD

**Issue by acelaya** [phpstan/phpstan-symfony#188]
This is kind of an edge case, and probably doesn't have an easy solution, but posting here in case there's some workaround that I may have missed.

Basically, I have some helper methods used to register and read options from a `Symfony\Component\Console\Input\InputInterface` object, in a way that both camelCase and kebab-case  names work (I used to define options in camelCase but I'm migrating to kebab-case. The former are deprecated but I need to continue supporting them until I release a new major version).

So, I have a `BaseCommand` class that looks like this, and all my commands extend from:

```php
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;

use function method_exists;
use function kebabCaseToCamelCase;
use function sprintf;
use function str_contains;

abstract class BaseCommand extends Command
{
    /**
     * @param string|string[]|bool|null $default
     */
    protected function addOptionWithDeprecatedFallback(
        string $name,
        ?string $shortcut = null,
        ?int $mode = null,
        string $description = '',
        bool|string|array|null $default = null,
    ): self {
        $this->addOption($name, $shortcut, $mode, $description, $default);

        if (str_contains($name, '-')) {
            $camelCaseName = kebabCaseToCamelCase($name);
            $this->addOption($camelCaseName, null, $mode, sprintf('[DEPRECATED] Alias for "%s".', $name), $default);
        }

        return $this;
    }

    /**
     * @return bool|string|string[]|null
     */
    protected function getOptionWithDeprecatedFallback(InputInterface $input, string $name): bool|string|array|null
    {
        $rawInput = method_exists($input, '__toString') ? $input->__toString() : '';
        $camelCaseName = kebabCaseToCamelCase($name);
        $resolvedOptionName = str_contains($rawInput, $camelCaseName) ? $camelCaseName : $name;

        return $input->getOption($resolvedOptionName);
    }
}
```

If I call `$someOption = $this->getOptionWithDeprecatedFallback($input, 'some-input-option')`, it does not infer the type properly from its definition.

If I read it as `$someOption = $input->getOption('some-input-option')`, then it does, and phpstan does not mark an error.

The funny thing is that it does detect the type used to register the option when I use `addOptionWithDeprecatedFallback`, because if I use that in combination with `$input->getOption(...)` it works.

**Comment by ondrejmirtes** [comment]
This is expected behaviour. This documentation page explains why: https://phpstan.org/user-guide/troubleshooting-types

In order to fix this, you need to replicate dynamic return type extension coming from phpstan-symfony modified for your own code.

**Comment by acelaya** [comment]
I'll take a look to that. Thanks for the tip.
