### ISSUE TITLE
Lazy Command

### ISSUE THREAD

**Issue by duboiss** [phpstan/phpstan-symfony#189]
Since `0.12.41` (#186), I have the following error:

```sh
Internal error: Internal error: There is currently no session available. in file ...Command.php
```

With `--debug`:
![image](https://user-images.githubusercontent.com/29716703/126615285-c4a17584-5934-4894-ac9e-4ef1bf7b6ee6.png)

I don't have this issue in `0.12.40`.

Line 130:
```php
foreach ($input->getArgument('groups') as $group) {
    try {
        $data = $this->loader->loadGroupByName($group);
```

Line 130 on another command which triggers error:
```php
if ($input->getOption('usage') && $checkpoint->getType() !== AbstractCheckpoint::CHECKPOINT_TYPE_USAGE) {
    continue;
}
```

So I think line 130 matches another file but the `--debug` exit on my commands.

I don't use the session anywhere by myself, I only make API calls under the hood.
My commands extends `Symfony\Component\Console\Command` and do not use the new php 8 attributes.

**Comment by ondrejmirtes** [comment]
Please somehow disable the Symfony error handler so that we can see the full stack trace and not just the exception rendered by Symfony.

**Comment by VincentLanglet** [comment]
> Since `0.12.41` (#186), I have the following error:
> 
> ```shell
> Internal error: Internal error: There is currently no session available. in file ...Command.php
> ```

When do you have this message ? When running phpstan ?

The error come from.
https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/HttpFoundation/RequestStack.php#L120-L126

Somehow the `getSession` method is called, but it would be nice to know why and where...

**Comment by duboiss** [comment]
> When do you have this message ? When running phpstan ?

Yes when running PHPStan, since `0.12.41`  as explained in the first line of the fist comment.

> Somehow the getSession method is called, but it would be nice to know why and where...
Yes but my command code has not changed.

I would need to get the PHPStan error and not symfony.
But I haven't managed to disable the Symfony error handler yet.

See if anyone else has the same problem shortly.

**Comment by VincentLanglet** [comment]
> I would need to get the PHPStan error and not symfony.
> But I haven't managed to disable the Symfony error handler yet (it's possible, sure ?).

I don't know you managed to get the Symfony error handler running during the phpstan analyse at the first place...

> See if anyone else has the same problem shortly.

If you have a repository to debug, it could help.

You can also try to change the code of the command, in order to see if it has impact on phpstan.
Removing all the code, half the code, and so on. Maybe a special line is making the phpstan crashing.
Knowing this special line could help.

**Comment by duboiss** [comment]
> I don't know you managed to get the Symfony error handler running during the phpstan analyse at the first place...

As far as I know there is nothing special in the project about this, but I will have an answer when I reproduce the code in a new repository.

Just to illustrate the situation

![image](https://user-images.githubusercontent.com/29716703/127783257-81ba5897-812c-413f-a9de-e192185a5efd.png)

> You can also try to change the code of the command, in order to see if it has impact on phpstan.
Removing all the code, half the code, and so on. Maybe a special line is making the phpstan crashing.
Knowing this special line could help.

Yeah I'll make time for it this week.

**Comment by ondrejmirtes** [comment]
Latest PHPStan version does not rely on registered exception handler, so you should always get a useful stack trace with --debug. So try it.

**Comment by duboiss** [comment]
> Latest PHPStan version does not rely on registered exception handler, so you should always get a useful stack trace with --debug. So try it.

`--debug` only gives me only the file name where the script returns an error.


I tried to reproduce the code on a blank project and didn't get the same "sessions" errors.
I assume that the basic project overrides some default behaviors.

Because no one else seems to have any problems since the update, I close this issue.

Thanks all
