### ISSUE TITLE
phpstan-symfony is no longer compatible with Symfony 4 because InputBag does not exist

### ISSUE THREAD

**Issue by zacharylund** [phpstan/phpstan-symfony#195]
See failures: https://github.com/phpstan/phpstan-symfony/runs/3393866713

Symfony 4.4 does not have the class Symfony\Component\HttpFoundation\InputBag and the additions in https://github.com/phpstan/phpstan-symfony/commit/95d9ae78605e5023e0edcf905c9b42da2a2a8359 expect that class to exist in the stub files.

**Comment by zacharylund** [comment]
I added this to a brand new Symfony 4.4 project:

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    /**
     * @Route("/test", name="test")
     */
    public function index(Request $request): Response
    {
        $foo = $request->query->get('foo');

        \PHPStan\dumpType($request->query);

        return $this->render('test/index.html.twig', [
            'controller_name' => 'TestController',
        ]);
    }
}
```

Running phpstan produces this output:

```
 ------ -------------------------------------------------------------------- 
  Line   Controller/TestController.php                                       
 ------ -------------------------------------------------------------------- 
  17     Call to method get() on an unknown class                            
         Symfony\Component\HttpFoundation\InputBag.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  19     Dumped type: Symfony\Component\HttpFoundation\InputBag<string>      
 ------ -------------------------------------------------------------------- 
```

**Comment by Mick3DIY** [comment]
I confirm in a Symfony project 4.4.26, phpstan 0.12.97, phpstan-symfony 0.12.43. Works fine before the last update ;)

**Comment by codegain** [comment]
Can also confirm: Symfony 4.4.30, phpstan 0.12.97 and phpstan-symfony 0.12.43 produces that output.
phpstan-symfony 0.12.42 works fine.

**Comment by jmleroux** [comment]
Same issue on https://github.com/akeneo/pim-community-dev

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-symfony/commit/c1627fce5b505b3f53d9d4fbd4d7963603305f98

Will need up-to-date phpstan/phpstan again.

**Comment by ondrejmirtes** [comment]
And released: https://github.com/phpstan/phpstan-symfony/releases/tag/0.12.44
