### ISSUE TITLE
Missing on Packagist

### ISSUE THREAD

**Issue by Majkl578** [phpstan/phpstan-symfony#2]
Please register this package on Packagist so it can be easily tested. :blush: 
https://packagist.org/packages/phpstan/phpstan-symfony _No packages found._

**Comment by lookyman** [comment]
This has to be done by @ondrejmirtes, I don't have access there. 😃

**Comment by ondrejmirtes** [comment]
Done 😊 https://packagist.org/packages/phpstan/phpstan-symfony

**Comment by lookyman** [comment]
Thanks!
