### ISSUE TITLE
Help getArgument/getOption in Symfony Console InputInterface

### ISSUE THREAD

**Issue by Jean85** [phpstan/phpstan-symfony#20]
Symfony had a few recent PRs to the Symfony console that impacted my PHPStan analysis due to PHPDoc changes:

https://github.com/symfony/symfony/pull/28448
https://github.com/symfony/symfony/pull/28374
https://github.com/symfony/symfony/pull/28647

Bottom line:
 * `InputInterface::getArgument` now returns `string|string[]|null`
 * `InputInterface::getOption` returns `string|string[]|bool|null`. 

In reality, they can return `string[]` only if the relative argument/option is set as `InputArgument::IS_ARRAY`/`InputOption::VALUE_IS_ARRAY`.

Is it possible to add an aid in this package for this case? The minimum repro case is this one:

```php
class PhpstanCommand extends \Symfony\Component\Console\Command\Command
{
    protected function configure()
    {
        $this->addArgument('argument', InputArgument::REQUIRED);
        $this->addOption('option', null, InputOption::VALUE_REQUIRED);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // Cannot cast array<string>|string|null to string. 
        $argument = (string) $input->getArgument('argument');
        // Cannot cast array<string>|bool|string|null to string. 
        $option = (string) $input->getOption('option');
    }
}
```

**Comment by lookyman** [comment]
I am not sure this is possible, since the options are set in a different method on different objects. This would probably require a much deeper analysis of the source code then I can imagine right now. But it is a really annoying thing to ignore these errors every time, so I can give it a go. Or you can always send a PR if you have an idea how to solve it..

**Comment by vasilvestre** [comment]
I really wonder how to configure it but PHP packages. The container isn't found and wrong types are still detected. Is there any change to do ?

**Comment by ondrejmirtes** [comment]
@vasilvestre You don't need a DI container to achieve this, you just need to return a configured Application instance from the `console_application_loader` file. Feel free to open a new issue if you have a specific problem with this.
