### ISSUE TITLE
Implementing DataTransformerInterface does not inherit types

### ISSUE THREAD

**Issue by mmarton** [phpstan/phpstan-symfony#204]
Hi!

```php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\DataTransformerInterface;

class CustomType extends AbstractType implements DataTransformerInterface
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
    }

    public function transform($value): array
    {
        return [];
    }

    public function reverseTransform($value): string
    {
        return '';
    }
}
```

Before release 1.0 this code was fine, now phpstan-symfony tells me that 
"Method App\Form\Type\CustomType::transform() has parameter $value with no type specified."

the paramter has mixed typehint on the interface, and was inherited until now.

I know there can be breaking cheanges in a major release, but is this expected? Other interfaces don't behave like this.

**Comment by jvasseur** [comment]
This is because the 1.0.0 release added a `DataTransformerInterface` stub that redefine the interface with type parameters. 

Adding an `@implements DataTransformerInterface<string, array>` phpdoc to your class should fix the error but I agree that the error is quite confusing.

**Comment by ondrejmirtes** [comment]
You're supposed to be getting this error on level 6:

> Class CustomType implements generic interface DataTransformerInterface but does not specify its types: T, R

See: https://phpstan.org/r/f49f5e8a-2b93-4383-9ec8-9ac1338af46d

You should still fix it, but that doesn't actually help you to solve this issue: https://phpstan.org/r/ec5831ce-3074-49aa-bd3c-b03acf0198f3

You're supposed to type what's in the array. At the very least you should say `mixed[]` but anything more specific is welcome.
