### ISSUE TITLE
Private services in tests

### ISSUE THREAD

**Issue by darthf1** [phpstan/phpstan-symfony#213]
Hi!

After https://github.com/phpstan/phpstan-symfony/pull/211 I get a lot of `Service 'xxx' is private`, which is normally a good thing. But In my codebase I get these messages solely when I fetch services in my functional tests.

Example:
```php
$service = self::getContainer()->get('messenger.transport.default'),
```
Mesage:
```
Service "messenger.transport.default" is private.
```

https://symfony.com/doc/current/testing.html#retrieving-services-in-the-test states:
```
The container in static::getContainer() is actually a special test container. It gives you access to both the public services and the non-removed private services services.
```

So, I'm not sure whether these issues should be given by default for the test container as well. For now I can ignore these messages from my test folder.

**Comment by ondrejmirtes** [comment]
Please see if a change in the spirit of this PR works for you: https://github.com/phpstan/phpstan-symfony/pull/212

Thanks.

**Comment by darthf1** [comment]
Ah, yeah that should fix it. Closing since its already being worked on :)
