### ISSUE TITLE
Add return type to Command::getHelper

### ISSUE THREAD

**Issue by ossinkine** [phpstan/phpstan-symfony#217]
Recommended way (described in [the documentation](https://symfony.com/doc/current/components/console/helpers/questionhelper.html)) to use the console command helpers is to use `getHelper` method but PHPStan can't recognize the return type of `getHelper`.

For example, the code from the documentation
```php
class YourCommand extends Command
{
    public function execute(InputInterface $input, OutputInterface $output)
    {
        $helper = $this->getHelper('question');
        $question = new ConfirmationQuestion('Continue with this action?', false);

        if (!$helper->ask($input, $output, $question)) {
            return Command::SUCCESS;
        }
    }
}
```
will generate an error `Cannot call method ask() on mixed`.

Adding type hint `HandlerInterface` does not solve the issue because method `ask` exists only in `QuestionHelper`, so PHPStan should be more smart and understand that `$this->getHelper('question')` returns `QuestionHelper`.

**Comment by ondrejmirtes** [comment]
Heah, sure, no problem - this is a case for a dynamic return type extension (https://phpstan.org/developing-extensions/dynamic-return-type-extensions). Feel free to contribute it!
