### ISSUE TITLE
Services with parameterised `class` are not resolved

### ISSUE THREAD

**Issue by Wirone** [phpstan/phpstan-symfony#226]
I've installed `phpstan/phpstan-symfony` extension and analysed current codebase with configured container. I see many errors like `Property Foo::$bar (Bar) does not accept %foo.bar.service.class%` on `$this->bar = $this->container->get('foo.bar.service');` when service has definition with parameterised class:

```
foo.bar.service:
  class: '%foo.bar.service.class%'
```

Such service definition is totally correct. It seems like it can't be resolved properly.

FYI: We don't have full Symfony framework, we use `symfony/dependency-injection` and dump container similarly like framework does. I don't know if that matters, but I thought I should point it out.

**Comment by ondrejmirtes** [comment]
Looks like `%foo.bar.service.class%` is not expanded to the actual object class.

The code in question is here https://github.com/phpstan/phpstan-symfony/blob/4140813ebfe7536222b67652fb82f870606ef204/src/Type/Symfony/ServiceDynamicReturnTypeExtension.php#L57-L77 so feel free to debug it and see what's wrong.

**Comment by Wirone** [comment]
@ondrejmirtes I've started work on this but I struggle to prepare fix. I've added parameter and service to `tests/Symfony/container.xml`, added scenario to `PHPStan\Symfony\DefaultServiceMapTest::getServiceProvider()` and I see error:

```
vendor/bin/phpunit tests/Symfony/DefaultServiceMapTest.php --filter=testGetService#2
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 00:00.035, Memory: 6.00 MB

There was 1 failure:

1) PHPStan\Symfony\DefaultServiceMapTest::testGetService with data set #2 ('withParameterisedClass', Closure Object (...))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Foo'
+'%app.class%'

./phpstan/phpstan-symfony/tests/Symfony/DefaultServiceMapTest.php:55
./phpstan/phpstan-symfony/tests/Symfony/DefaultServiceMapTest.php:17
```

But when I work with XDebug I don't see that it goes through mentioned `ServiceDynamicReturnTypeExtension::getGetTypeFromMethodCall()` method. I see that services are resolved in `XmlServiceMapFactory` and are stored in `DefaultServiceMap`. Should parameterised class be resolved on this level? If not, could you help me where should I start (create new rule, add test case to another existing test class)?
