### ISSUE TITLE
consoleApplicationLoader not recognized

### ISSUE THREAD

**Issue by villfa** [phpstan/phpstan-symfony#231]
Hi,

I have this error:
```sh
 ./vendor/bin/phpstan
Note: Using configuration file /<edited>/phpstan.neon.
Invalid configuration:
Unexpected item 'parameters › symfony › consoleApplicationLoader', did you mean 'console_application_loader'?
```

Here the content of `phpstan.neon`:
```
parameters:
  symfony:
    consoleApplicationLoader: %currentWorkingDirectory%/tests/console-application.php
```

If I replace `consoleApplicationLoader` by `console_application_loader` it works fine.
According the README file we should use `consoleApplicationLoader`, so I was wondering if it's a bug or a documentation problem.

Versions:
* phpstan/phpstan: 1.3.3
* phpstan/phpstan-symfony: 1.0.6

**Comment by ondrejmirtes** [comment]
Version that corresponds to the new README hasn't been released yet.
