### ISSUE TITLE
PSR-11 Container and AbstractController support

### ISSUE THREAD

**Issue by luxemate** [phpstan/phpstan-symfony#26]
https://github.com/symfony/framework-bundle/blob/master/Controller/Controller.php is marked as deprecated since 4.2 and there is a new way of defining a controller through https://github.com/symfony/framework-bundle/blob/master/Controller/AbstractController.php. 

It also uses PSR-11 Container interface https://github.com/php-fig/container/blob/master/src/ContainerInterface.php, so currently phpstan not being able to find services.

**Comment by tomasfejfar** [comment]
Should I make a PR for this or are you already working on it?

**Comment by tomasfejfar** [comment]
@lookyman @luxemate ?

**Comment by lookyman** [comment]
@tomasfejfar If you make a PR, I will be most grateful, thanks!

**Comment by tomasfejfar** [comment]
I'll see what I can do.

**Comment by tomasfejfar** [comment]
I'm on it :)
