### ISSUE TITLE
PHPstan does not find container helper functions

### ISSUE THREAD

**Issue by Khartir** [phpstan/phpstan-symfony#269]
After upgrading to PHPStan 1.6, the following errors are reported when analyzing the config files:
```
Used function Symfony\Component\DependencyInjection\Loader\Configurator\service not found.
```
Workaround: Add `vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php` to the `scanFiles`.

I'm unsure if this is a bug or just something that should be added to the README.

**Comment by ondrejmirtes** [comment]
This is expected behaviour: https://github.com/phpstan/phpstan/issues/7118

It'd be best to fix this in Symfony. But you can send a PR to README here as well.

**Comment by ondrejmirtes** [comment]
Hi @Khartir I have an idea how to make this error go away even without a special extra configuration, but can you please reproduce it in a small repository so I can verify my fix? Thanks.

**Comment by Khartir** [comment]
Here you go: https://github.com/Khartir/phpstan-symfony-di-helper-reproduction
One thing I realized: the error only occurs with bleeding edge enabled. Not sure if you're aware of this. I assume this is due to using static reflection?

**Comment by ondrejmirtes** [comment]
I'm happy to announce this example works since PHPStan 1.6.6 without any special need for `scanFiles` configuration 🎉  Thanks!
