### ISSUE TITLE
False positive in Tests: Service XY is private

### ISSUE THREAD

**Issue by Pierstoval** [phpstan/phpstan-symfony#27]
When using the `KernelTestCase` and asking PhpStan to analyze a test, I have this error:

![image](https://user-images.githubusercontent.com/3369266/49603146-bc9cdd00-f98a-11e8-9e7d-6eff7c8cbe69.png)

However, the `static::$container` that is in the `KernelTestCase` is supposed to be an instance of the `TestContainer` but is typed as `ContainerInterface` because it might happen that the `test.container` service can be absent from the container, therefore making `static::$container` be the full container (as of [KernelTestCase here](https://github.com/symfony/symfony/blob/8f36bbd/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L87) )

Here is the code that triggers the error: [Pierstoval/AgateApps/.../RedeemerTest.php#L61-L79](https://github.com/Pierstoval/AgateApps/blob/aa3cd13bb4f496efd47fd722ab6941b7404a041d/tests/Voucher/Redeem/RedeemerTest.php#L61-L79)

If the `test.container` service exists in the container AND for this specific case, I think there shouldn't be any error.

**Comment by lookyman** [comment]
I plan to try to tackle these false positives in the near future. It's... difficult. Symfony container is not as straightforward as I imagined when I started working with it and writing this extension. 😊

**Comment by Pierstoval** [comment]
By chance there are not _that many_ errors with the container 👍

**Comment by Wirone** [comment]
I was struggling with this too, but @Pierstoval's solution worked for me. Maybe it's not as clean as it should be, but resolves my CI issue :) Subscribing to this, so hopefully it can be replaced with proper solution on some point.

**Comment by mitelg** [comment]
plus 1 :blush: 
would be nice, if this could be fixed somehow

@Pierstoval's solution also worked for me in the meantime :+1:

**Comment by jeroennoten** [comment]
I created #210 to resolve this issue.

**Comment by ondrejmirtes** [comment]
Fixed by: https://github.com/phpstan/phpstan-symfony/pull/210

Merged and released :)

**Comment by Pierstoval** [comment]
By the way, the exact same will happen to `KernelTestCase::getContainer()` method, because using `self::$container` is now deprecated as of Symfony 5.3 😅

**Comment by ondrejmirtes** [comment]
Feel free to send another PR :)

**Comment by Pierstoval** [comment]
@ondrejmirtes Is that it? => https://github.com/phpstan/phpstan-symfony/pull/212

I have no knowledge on how phpstan works, I just took example on #210, I have no idea on whether it's right or not 😅
