### ISSUE TITLE
Symfony HttpFoundation 6.1 issue

### ISSUE THREAD

**Issue by tarlepp** [phpstan/phpstan-symfony#281]
After I updated to Symfony 6.1.0 I noticed following errors when I run PHPStan:

```bash
 ------ ------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   tools/02_phpstan/vendor/phpstan/phpstan-symfony/src/Symfony/../../stubs/Symfony/Component/HttpFoundation/Request.stub                     
 ------ ------------------------------------------------------------------------------------------------------------------------------------------ 
  32     Method Symfony\Component\HttpFoundation\Request::getSession() has invalid return type Symfony\Component\HttpFoundation\SessionInterface.  
         ✏️  tools/02_phpstan/vendor/phpstan/phpstan-symfony/src/Symfony/../../stubs/Symfony/Component/HttpFoundation/Request.stub                 
  32     PHPDoc tag @return with type Symfony\Component\HttpFoundation\Session\Session is not subtype of native type                               
         Symfony\Component\HttpFoundation\SessionInterface.                                                                                        
         ✏️  tools/02_phpstan/vendor/phpstan/phpstan-symfony/src/Symfony/../../stubs/Symfony/Component/HttpFoundation/Request.stub                 
 ------ ------------------------------------------------------------------------------------------------------------------------------------------ 
```

It looks like return type has been changed in this update.

**Comment by Robert-Bartel** [comment]
I think the error is in this file: `vendor/phpstan/phpstan-symfony/stubs/Symfony/Component/HttpFoundation/Request.stub`

```
<?php

namespace Symfony\Component\HttpFoundation;

class Request
{

	/**
	 * Request body parameters ($_POST).
	 *
	 * @var InputBag<string|int|float|bool>
	 */
	public $request;

	/**
	 * Query string parameters ($_GET).
	 *
	 * @var InputBag<string>
	 */
	public $query;

	/**
	 * Cookies ($_COOKIE).
	 *
	 * @var InputBag<string>
	 */
	public $cookies;

    /**
     * @return \Symfony\Component\HttpFoundation\Session\Session
     */
    public function getSession(): SessionInterface;

}
```

The return value of getSession() is SessionInterface. But it is in the wrong namespace: `Symfony\Component\HttpFoundation`.

The correct one would be `Symfony\Component\HttpFoundation\Session`.

**Comment by ondrejmirtes** [comment]
I had it fixed for several days already but haven't tagged a release. The reason is that I thought this error report shows up only when analysing phpstan-symfony itself and it wouldn't influence users running PHPStan on their projects.

I don't know your project structure and what `tools/02_phpstan/vendor/phpstan` is but it looks quite exotic. The recommended way of running PHPStan and its extensions is to put them inside `require-dev` in your project's `composer.json`.

Here's the new tagged release: https://github.com/phpstan/phpstan-symfony/releases/tag/1.2.3

**Comment by Robert-Bartel** [comment]
Perfect. I just used tag 1.2.3 and it works! 👍

**Comment by tarlepp** [comment]
I can confirm that version `1.2.3` fixes this - thanks!

@ondrejmirtes I'm using https://github.com/bamarni/composer-bin-plugin to organize all dev tools to own "namespaces" - that is why that directory structure might look a bit weird.

**Comment by ondrejmirtes** [comment]
Completely unnecessary, even counterproductive, to do that for PHPStan 😊
