### ISSUE TITLE
Catch accessing the session in a constructor

### ISSUE THREAD

**Issue by ThomasLandauer** [phpstan/phpstan-symfony#292]
With a constructor like this:

```php
use Symfony\Component\HttpFoundation\RequestStack;

public function __construct(RequestStack $requestStack)
{
    $this->session = $requestStack->getSession();
}
```

... phpstan is crashing with:

> Internal error: Internal error: There is currently no session available. in file ...

It looks like it's not allowed to access the session in a constructor; I opened a PR at symfony-docs: https://github.com/symfony/symfony-docs/pull/16985

**Comment by ondrejmirtes** [comment]
Can you show me the stack trace of the internal error so I can decide if it's fixable?

**Comment by ThomasLandauer** [comment]
Sorry, I can't reproduce this - so I'm closing it.
