### ISSUE TITLE
Symfony 4.4 is maintained for another 15 months

### ISSUE THREAD

**Issue by zacharylund** [phpstan/phpstan-symfony#304]
The [Symfony roadmap](https://symfony.com/releases) says that 4.4 is maintained through November 2023 and Symfony 6.0 is maintained through January 2023.

https://github.com/phpstan/phpstan-symfony/commit/298f7aee5f36f7d72e575970013b46965456b7f4 removes support for Symfony 4.x including 4.4.
https://github.com/phpstan/phpstan-symfony/commit/120d3a8f3b16f79a570e4ef68a96fe9f85186fd1 adds support for Symfony 6.1 but does not include 6.0.

It seems premature to remove support for Symfony 4.4.

Also, https://github.com/phpstan/phpstan-symfony/commit/a14d467083e8a4ca6860921e68f646831a88260c isn't compatible with Symfony 4.4

**Comment by ondrejmirtes** [comment]
At the top of the page it says LTS release is 5.4.11.

It's a nightmare to support such a big range of releases (meaning 4.x to 6.x), that's why I decided to make my maintenance easier.

Symfony 4.4 has been released almost 3 years ago, you really ought to upgrade to a newer version.

**Comment by zacharylund** [comment]
Fair enough. Thanks for explaining.

**Comment by ondrejmirtes** [comment]
FYI I accepted a quickfix https://github.com/phpstan/phpstan-symfony/pull/305
