### ISSUE TITLE
$container->has() always true

### ISSUE THREAD

**Issue by ToBee94** [phpstan/phpstan-symfony#31]
If I use $container->has() in a CompilerPass, php-stan says that is always true.

Example:

```
<?php declare(strict_types=1);

namespace Project\Web\CompilerPass;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class ExceptionHandlerPass implements CompilerPassInterface
{

    public function process(ContainerBuilder $container)
    {
        if (!$container->has("project.exception_listener")) {
            $definition = $container->findDefinition("project.exception_listener");

            $taggedServices = $container->findTaggedServiceIds("project.exception_listener.handler");

            foreach ($taggedServices as $id => $taggedService) {
                $definition->addMethodCall("addExceptionHandler", [new Reference($id)]);
            }
        }
    }
}
```

Error:
```
 ------ ------------------------------------------- 
  Line   src/CompilerPass/ExceptionHandlerPass.php  
 ------ ------------------------------------------- 
  14     Negated boolean is always false.           
 ------ ------------------------------------------- 
```

Without the Symfony Plugin it works.

**Comment by alcaeus** [comment]
I assume you configured a `project.exception_listener` in your container? The bundle checks the compiled container to infer return types of the `has` and `get` methods, which is why you'll get that error message.

**Comment by ToBee94** [comment]
yes the service is defined in the config. 

They are two problems:

The check ensures that the service has been loaded correctly and a check that the service was ever defined. What if the pass should only be used if the service has been defined? 
Also what if I deregister the service in other passes or listener?

**Comment by alcaeus** [comment]
I'm not saying whether or not it's correct, I'm merely saying why you get the error. This is what this library does: it inspects your container and tells you that the service is there so you don't need to check for its existence.

**Comment by lookyman** [comment]
> What if the different environments have different defined services?

You can pass different paths to respective environment containers in different configs and run PHPStan with those. For example, I always use a special `phpstan.tests.neon` config for my tests, which just includes the normal config and redefines the container path to the test one.

However, there is an other way, check out [this](https://github.com/phpstan/phpstan-symfony#constant-hassers) part of the README.

**Comment by Wirone** [comment]
I got this error when I wanted to override some listener's priority and was checking if it's registered by using `has()`. I needed to check it because that listener is registered dynamically based on configuration - for current config it's always enabled.

I changed PHPStan's Symfony extension config by disabling [`constant_hassers`](https://github.com/phpstan/phpstan-symfony#constant-hassers) and it's working :)
