### ISSUE TITLE
Remove nullable type after calling `HeaderBag::has` is breaking logic

### ISSUE THREAD

**Issue by icanhazstring** [phpstan/phpstan-symfony#316]
With the latest release 1.2.17 removing nullable from `HeaderBag::get` is not working correctly.
The header can still exist but the value can be null. If that happens we now can't check for null values.

Commit in question: https://github.com/phpstan/phpstan-symfony/commit/738920755edd12c693ae83ab73b8f6bfa220a091

```
foreach ($this->supportHeaders as $name) {
    if (!$request->headers->has($name)) {
        continue;
    }

    $headerValue = $request->headers->get($name);
    if ($headerValue === null) { // this will be reported as "always false" but shouldn't
        continue;
    }

    $list[] = new Attribute($name, $headerValue);
}
```

**Comment by ondrejmirtes** [comment]
How does the HTTP request look like if the header is set, but the value is null?

**Comment by icanhazstring** [comment]
It doesn't have to come through the means of HTTP only.
It could be set using code directly as well, in that case, a `null` value is possible.

Edit:
As symfony itself inside the `Request` object while creating the `HeaderBag` is allowing `null` values either way it could always be possible.

**Comment by icanhazstring** [comment]
It happens in these lines:

```
public function get(string $key, string $default = null)
{
    $headers = $this->all($key);

    if (!$headers) {
        return $default;
    }

// Right here is the problem
    if (null === $headers[0]) {
        return null;
    }

    return (string) $headers[0];
}
```

**Comment by ondrejmirtes** [comment]
Alright, reverting. Thanks!

**Comment by ondrejmirtes** [comment]
Fixed by https://github.com/phpstan/phpstan-symfony/commit/3178f15a60b62df21ddd202f6a668851eeb138c7.

/cc @franmomu

**Comment by franmomu** [comment]
didn't know it allows `null`, thanks for reporting 👍 and fixing it

**Comment by icanhazstring** [comment]
I think the extension from you is not completely wrong. But it would behave a little different:

- if ::has($a) is true
- ::get($a) will return a nullable value

But the difference is in the default value type:
- if ::has($a) is false
- ::get($a, 1) will return int
- checking value against anything other than string is always false
