### ISSUE TITLE
AbstractType generics in psalm but not in phpstan

### ISSUE THREAD

**Issue by kissifrot** [phpstan/phpstan-symfony#320]
Hello,

I'm having issues with cross-usage of psalm and phpstan for form type classes extending `AbstractType`:
- on psalm (v5) side with [psalm-plugin-symfony](https://github.com/psalm/psalm-plugin-symfony),  it's considered generic, thus adding the annotation `/** @extends AbstractType<mixed> */` (or similar ^^) is needed to avoid getting `MissingTemplate` errors
- on phpstan side with [phpstan-symfony](https://github.com/phpstan/phpstan-symfony) phpstan will complain that `AbstractType` is not generic

I'm a bit lost in this situation, as I guess suppressing psalm's `MissingTemplate` errors is not the good thing to do 😅

**Comment by ondrejmirtes** [comment]
Hi, please show an example of a class that uses `AbstractType`. What's the advantage of AbstractType being generic?

**Comment by kissifrot** [comment]
To be honest I'm not sure about this specific addition, but it sems it raises issues such as the one described in https://github.com/psalm/psalm-plugin-symfony/issues/295#issuecomment-1359526555

An example class would be:
```php
// ...
use Symfony\Component\Form\AbstractType;

class UserBookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, ['trim' => true])
// 
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UserBookCreateDTO::class,
        ]);
    }
}
```

To then be used in symfony's `AbstractController`:
```php
        // ...
        $userBookDTO = new UserBookCreateDTO();
        $form = $this->createForm(UserBookType::class, $userBookDTO);
        $form->handleRequest($request);
        // ...
```

**Comment by VincentLanglet** [comment]
There already was a PR opened for this https://github.com/phpstan/phpstan-symfony/pull/317

And I explained that the stub/generics is currently useless for PHPStan https://github.com/phpstan/phpstan-symfony/pull/317#pullrequestreview-1227793157

The solution is maybe to write
```
/** 
 * @psalm-extends AbstractType<Foo>
 * @phpstan-extends AbstractType
 */
```

**Comment by ondrejmirtes** [comment]
That suggestion isn't going to work. Please before you suggest something, check it with phpstan.org/try.

The solution is https://phpstan.org/user-guide/ignoring-errors

**Comment by VincentLanglet** [comment]
> That suggestion isn't going to work. Please before you suggest something, check it with phpstan.org/try.

Indeed, it works for param/return type but not for extends
https://phpstan.org/r/767eb0ad-18ea-47a1-a204-f027169c5fa3

Dunno if it's worth enough for a feature request...

**Comment by ondrejmirtes** [comment]
This PR looks promising https://github.com/phpstan/phpstan-symfony/pull/337
