### ISSUE TITLE
Call to an undefined method Symfony\Component\Validator\ConstraintViolationListInterface::__toString()

### ISSUE THREAD

**Issue by MichaelBrauner** [phpstan/phpstan-symfony#344]
I get this error: 

`Call to an undefined method Symfony\Component\Validator\ConstraintViolationListInterface::__toString()`

But `__toString()` actually should be implemented: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Validator/ConstraintViolationListInterface.php#L24

**Comment by ondrejmirtes** [comment]
The `@method` is missing here, please send a PR that syncs the stub: https://github.com/phpstan/phpstan-symfony/blob/1.2.x/stubs/Symfony/Component/Validator/ConstraintViolationListInterface.stub

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-symfony/pull/356
