### ISSUE TITLE
Method MyVoter::supports() has parameter $attribute with no type specified

### ISSUE THREAD

**Issue by luxemate** [phpstan/phpstan-symfony#367]
After update from 1.1.8 to 1.3.4 all custom voters started producing an error, although Symfony's abstract Voter has type annotation for $attribute:

> Method MyVoter::supports() has parameter $attribute with no type specified.

Consider the following simple Voter implementation:

```php
use Symfony\Component\Security\Core\Authorization\Voter\Voter;

class MyVoter extends Voter
{
    protected function supports($attribute, mixed $subject): bool
    {
        return true;
    }

    protected function voteOnAttribute($attribute, mixed $subject, TokenInterface $token): bool
    {
        return true;
    }
}
```

The funny thing is it only gets upset by the `supports` method, but not the `voteOnAttribute` method.

![image](https://github.com/phpstan/phpstan-symfony/assets/1465003/020c40ba-064c-4c7d-a6ae-3e6ce3c9f510)

**Comment by ondrejmirtes** [comment]
Hi, this is not a bug. Your method should be declared such as:

```php
protected function supports(string $attribute, mixed $subject): bool
```

Same as the parent. If you widen the type by omitting the parameter type on purpose, you should say in the PHPDoc what the type is supposed to be, such as `@param mixed $attribute`.

**Comment by luxemate** [comment]
@ondrejmirtes Symfony 4.4 doesn't have native types set, thus I also can't use native type in `supports` (because of the signature mismatch). But what symfony does have is the `@param string $attribute` set, which is ignored in the `supports` method, but is not ignored in the `voteOnAttribute` method (probably because of asserts in the stub). 

But maybe I misinterpret the situation and with `treatPhpDocTypesAsCertain: false` it's required to add `@param string $attribute`  to the `supports` method in a custom `Voter`. Though it seems a little bit redundant, as annotation was already added by the third-party vendor.

**Comment by ondrejmirtes** [comment]
@luxemate You've left out the information about Symfony 4.4 in your issue. I'd accept a PR that adds `@param string $attribute` into the stub.

**Comment by luxemate** [comment]
@ondrejmirtes I've created a new PR and added only `@param string $attribute` as you've suggested.
