### ISSUE TITLE
[Question] Does debug have to be enabled to get xml file generated?

### ISSUE THREAD

**Issue by robertfausk** [phpstan/phpstan-symfony#37]
If you run your project with debug=false then var/cache/dev/srcApp_KernelDevDebugContainer.xml doesn't seem to be generated.

In my case I've build a container with docker and debug disabled.
![image](https://user-images.githubusercontent.com/1651297/53023452-95b85800-345d-11e9-9710-eba2d24c72f8.png)

**Comment by jvasseur** [comment]
The XML is dumped by the [ContainerBuilderDebugDumpPass](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php) which is added [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L132) so yes, it's only dumped in debug mode.

**Comment by lookyman** [comment]
Yep, as @jvasseur says.

I've considered several times to add some different provider that could maybe load the services from a different source (like the compiled class from `srcApp_KernelDevContainer.php`), but so far I haven't had the need for it.
