### ISSUE TITLE
[Feature Request] Enforce `ResetInterface` on non-read-only services

### ISSUE THREAD

**Issue by priyadi** [phpstan/phpstan-symfony#380]
I'm proposing this rule: if a class is in the container, then it must either be read-only/immutable, or implement `ResetInterface`.

This rule will help to ensure our code is ready for worker mode (Swoole, FrankenPHP, RoadRunner, etc).

**Comment by ondrejmirtes** [comment]
Hello, this is too opinionated because traditional apps don't need it.

But you can always implement a custom rule (and even publish it as your own package) 😊
