### ISSUE TITLE
PHPstan does not find container helper functions used on packages php configs

### ISSUE THREAD

**Issue by thePanz** [phpstan/phpstan-symfony#381]
Similar (but solved) issue: https://github.com/phpstan/phpstan-symfony/issues/269 , where the helper functions are used in the `services.php` file.

In this issue, the error is triggered when helper functions are used in a package configuration file (the ones under `config/packages/**.php`).

Example:

```php
# config/packages/messenger.php
<?php

declare(strict_types=1);

use App\Infrastructure\Symfony\Messenger\AsyncMessage;
use Symfony\Config\FrameworkConfig;

use function Symfony\Component\DependencyInjection\Loader\Configurator\env;

return static function (FrameworkConfig $framework): void {
    $messenger = $framework->messenger()->failureTransport('failed');
    $messenger->transport('async')->dsn(env('MESSENGER_TRANSPORT_DSN'));
}:
```

Phpstan error: 
> Used function Symfony\Component\DependencyInjection\Loader\Configurator\env not found

The solution is to re-add the `scanFile` configuration to phpstan.neon, as initially documented in https://github.com/phpstan/phpstan-symfony/pull/271

Note: that the documentation was added in b1c5152, but then removed in 94e6c34

**Comment by ondrejmirtes** [comment]
This is not PHPStan's fault, but Symfony's. These functions aren't discoverable by the autoloader. The root issue should be fixed in the framework.

**Comment by thePanz** [comment]
Thanks @ondrejmirtes , I agree that it is a SF issue :+1: 

Anyhow:
- how was it solved in https://github.com/phpstan/phpstan-symfony/issues/269#issuecomment-1118467915 ?
- should we re-introduce the documentation in the readme, thus restore commit b1c5152? this would help other developers to solve the problem 

WDYT?

**Comment by ondrejmirtes** [comment]
> how was it solved

See the release notes for PHPStan 1.6.6: https://github.com/phpstan/phpstan/releases/tag/1.6.6

> should we re-introduce the documentation

Yeah, sure

**Comment by thePanz** [comment]
> > should we re-introduce the documentation
> 
> Yeah, sure

I created a PR here: https://github.com/phpstan/phpstan-symfony/pull/382
