### ISSUE TITLE
wrong asumption about `InputInterface::getArgument()` return type in `interact()`

### ISSUE THREAD

**Issue by nikophil** [phpstan/phpstan-symfony#396]
Hello,

since [this PR](https://github.com/phpstan/phpstan-symfony/pull/391), if the config `symfony.consoleApplicationLoader` is not provided, PHPStan will always consider that every call to `$input->getArgument()` inside the method `interfact()` will return null.

Maybe some guard condition should be added gefore adding `NullType`.

I'm willing to fix this if you think it is relevant

**Comment by VincentLanglet** [comment]
> PHPStan will always consider that every call to `$input->getArgument()` inside the method `interfact()` will return null.
> 
> Maybe some guard condition should be added gefore adding `NullType`.

I made some new tries and
```
$this->addArgument('task', InputArgument::REQUIRED); // Possibly null in interact
$this->addArgument('task', InputArgument::REQUIRED | InputArgument::ARRAY); // [] in interact
$this->addArgument('task', InputArgument::REQUIRED, default: 'foo'); // Not possible
$this->addArgument('task', InputArgument::OPTIONAL); // Possibly null in interact
$this->addArgument('task', InputArgument::OPTIONAL, default: 'foo'); // Not null in interact
```

And also, indeed, we need to add Null only if some types were already inferred.

I opened https://github.com/phpstan/phpstan-symfony/pull/397

**Comment by ondrejmirtes** [comment]
Please test 1.4.4 https://github.com/phpstan/phpstan-symfony/releases/tag/1.4.4 to see whether it fixes your problem.

**Comment by nikophil** [comment]
problem fixed :heavy_check_mark: 

thanks!
