### ISSUE TITLE
Process generator produces mixeds instead of strings

### ISSUE THREAD

**Issue by rudiedirkx** [phpstan/phpstan-symfony#413]
- symfony/process: v6.4.12
- phpstan/phpstan: 1.12.6

With `Process.stub` intact:

```php
foreach ( $process as $type => $buffer ) {
	\PHPStan\dumpType($type); // mixed
	\PHPStan\dumpType($buffer); // mixed
}
```

Same for `$process->getIterator()`.

If I change the class name in the stub, so it doesn't do anything, both `$type` and `$buffer` are `string`.

Maybe because symfony's `Process` already does correct annotations? In the class phpdoc and `getIterator()` phpdoc.

I'm okay with a local hack. How do I fix my Process generator?

**Comment by ondrejmirtes** [comment]
This should fix it: https://github.com/phpstan/phpstan-symfony/commit/270c2ee1478d1f8dc5121f539e890017bd64b04c

Please try it out in the latest 1.4.11 release.
