### ISSUE TITLE
Using the new SF4.3 EventDispatcher::dispatch method signature throws en error

### ISSUE THREAD

**Issue by tifabien** [phpstan/phpstan-symfony#59]
When using the new SF4.3 EventDispatcher::dispatch method signature (https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching) it fails when using the second optional eventName parameter.

The error is the following :
```
Method                                                                  
         Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch()  
         invoked with 2 parameters, 1 required. 
```

**Comment by ondrejmirtes** [comment]
How does the method signature and body look like on your disk?

**Comment by tifabien** [comment]
Seems the same as this one https://github.com/symfony/symfony/blob/4.3/src/Symfony/Contracts/EventDispatcher/EventDispatcherInterface.php

**Comment by ondrejmirtes** [comment]
Yeah, there's no way to solve this on PHPStan side. I recommend to add it to ignoreErrors.

**Comment by tifabien** [comment]
OK That's what I already added but in case I was not sure whether we could do something.
Thanks !
