### ISSUE TITLE
Support Symfony 5

### ISSUE THREAD

**Issue by Gradius30** [phpstan/phpstan-symfony#67]
Hello, would it be possible to update dependencies requirements to support Symfony 5 distribution?

I am currently having a problem with ` phpstan/phpstan 0.11.19 requires symfony/console ~3.2 || ~4.0 -> no matching package found`

To solve this `symfony/console ^5.0` would be welcomed

However I believe there are more packages that would benefit from getting updated

**Comment by ondrejmirtes** [comment]
Install `phpstan/phpstan:0.12` once I tag it later today.
