### ISSUE TITLE
Fatal Error Uncaught Type Error

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-symfony#71]
# Bug report

Analysing [this class](https://github.com/shopware/platform/blob/6.1/src/Core/Framework/Struct/Serializer/StructNormalizer.php) gives the following error: 

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPStan\Analyser\MutatingScope::getType() must be an instance of PhpParser\Node\Expr, null given, called in development/dev-ops/analyze/vendor-bin/phpstan/vendor/phpstan/phpstan-symfony/src/Type/Symfony/SerializerDynamicReturnTypeExtension.php on line 42 and defined in phar:///development/dev-ops/analyze/vendor-bin/phpstan/vendor/phpstan/phpstan/phpstan/src/Analyser/MutatingScope.php:276
Stack trace:
#0 development/dev-ops/analyze/vendor-bin/phpstan/vendor/phpstan/phpstan-symfony/src/Type/Symfony/SerializerDynamicReturnTypeExtension.php(42): PHPStan\Analyser\MutatingScope->getType(NULL)
phpstan/phpstan#1 phar:///development/dev-ops/analyze/vendor-bin/phpstan/vendor/phpstan/phpstan/phpstan/src/Analyser/MutatingScope.php(2207): PHPStan\Type\Symfony\SerializerDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ObjectTypeMethodReflection), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScop in phar:///development/dev-ops/analyze/vendor-bin/phpstan/vendor/phpstan/phpstan/phpstan/src/Analyser/MutatingScope.php on line 276

### Code snippet that reproduces the problem

Happens here https://github.com/shopware/platform/blob/6.1/src/Core/Framework/Struct/Serializer/StructNormalizer.php
But I don't know the exact place. If you need more information, please let me know

**Comment by lookyman** [comment]
I'll take a look, thanks!

**Comment by lookyman** [comment]
Well, at the first glance, the problem appears to be here:

`public function denormalize($data, $type = null, $format = null, array $context = [])`

The `$type` argument is supposed to be `string`, according to the denormalizer interface.

**Comment by lookyman** [comment]
Fixed eb4ceaa979993da504d719ffe5ab8bb44c266f15
