### ISSUE TITLE
get correct User class?

### ISSUE THREAD

**Issue by garak** [phpstan/phpstan-symfony#81]
It would be nice it this plugin could allow to get User class declared in configuration (e.g. in `config/packages/security.yaml`), so it can be retrieved instead of generic `\Symfony\Component\Security\Core\User\UserInterface`.

Tipical scenarios are getting User calling `$this->getUser()` from controller and calling `$tokenStorage->getToken()->getUser()` from a service where token storage is injected.

**Comment by b1rdex** [comment]
A workaround: add a stub in your project, something like this:

```php
<?php

namespace Symfony\Bundle\FrameworkBundle\Controller {
    class AbstractController
    {
        /**
         * @return \App\Entity\User
         */
        protected function getUser()
        {
        }
    }
}

namespace App\Entity {
    class User // yes, the User class must be present in the stubs too
    {
    }
}
```

**Comment by ondrejmirtes** [comment]
I've seen a similar question elsewhere and I've seen it solved with `#[CurrentUser]` attribute: https://symfony.com/blog/new-in-symfony-5-2-controller-argument-attributes

**Comment by b1rdex** [comment]
@ondrejmirtes I feel like the issue should be reopened - the attribute you mentioned works only in controllers. There are also `Symfony\Component\Security\Core\Security::getUser()` and `Symfony\Component\Security\Core\Authentication\Token::getUser()`.

**Comment by ondrejmirtes** [comment]
If you have a suggestion I'll welcome a PR :)
