### ISSUE TITLE
Load different containers for different directories

### ISSUE THREAD

**Issue by greg0ire** [phpstan/phpstan-symfony#85]
Somewhat related to #84, cc @gmponos

On a fresh Symfony app, `config/services_test.yaml` looks like this:

```
    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    test.App\Core\Domain\GetEngineList: '@App\Core\Domain\GetEngineList'
```

Later, in tests, I will try to access this service that is only available in the test container. To avoid issues with PHPstan, I configured the extension to use the test container, maybe that should become the default recommendation? And maybe there should be a way to use it only for the `tests` directory, while using the dev or prod container for the `src` directory?

**Comment by gmponos** [comment]
FYI what I currently do in my projects is that I have two make commands:

``` makefile
phpstan-src:
	APP_ENV=dev php bin/console cache:clear
	php vendor/bin/phpstan analyse -c phpstan.src.neon ./src

phpstan-tests:
	APP_ENV=test php bin/console cache:clear
	php vendor/bin/phpstan analyse -c phpstan.tests.neon ./tests
```

Each one loading a different container... maybe if different containers could be loaded per path 🤔 ?

**Comment by ondrejmirtes** [comment]
Yes, these needs are covered by running PHPStan multiple times with different configs.

**Comment by gmponos** [comment]
> Yes, these needs are covered by running PHPStan multiple times with different configs.

never the less if someone was willing to take this task.. would you accept this modification? meaning a different container per path?

**Comment by ondrejmirtes** [comment]
Nope, I don't think it's necessary. Thanks.

**Comment by greg0ire** [comment]
> maybe that should become the default recommendation?

I think in most cases the test container is a superset of the dev container, maybe the README should be changed? I can make the PR.
