### ISSUE TITLE
services should not be case sensitive 

### ISSUE THREAD

**Issue by Szpadel** [phpstan/phpstan-symfony#9]
it is common pattern to name services as class path, and then select them with `SomeClass::class`.

symfony converts those dependencies to lower case before saving / resolving.

This causing errors like `Service "SomeNamespace\SomeClass" is not registered in the container.`

because in `appDevDebugProjectContainer.xml` it is saved as: `somenamespace\someclass`

**Comment by lookyman** [comment]
Hi, can you please confirm that this is a problem in Symfony 3? Because 4 seems to work as expected.

**Comment by Szpadel** [comment]
this is actually still symfony 2.8... but I believe that in most modern version resolution is still case insensitive

**Comment by lookyman** [comment]
Ahh, 2.8, that explains a lot, I've never used such an old version. Ok, I'll see what I can do about it. Thanks.

**Comment by ondrejmirtes** [comment]
How you managed to install this extension along Symfony < 3.0 I don't understand 😊

**Comment by lookyman** [comment]
I do. We have conflict for an old framework-bundle, but Symfony 2 does not use that. This all comes from my lack of experience with older Symfony, I only ever started tu use it just about the time 4 came along. 😊

**Comment by Szpadel** [comment]
We are using phpstan in docker, so we don't have to deal with conflicts ;-)

**Comment by lookyman** [comment]
Closing as invalid, since we don't support Symfony 2.
