### ISSUE TITLE
http-foundation InputBag::get with default value should not return null

### ISSUE THREAD

**Issue by raalderink** [phpstan/phpstan-symfony#91]
If you use HTTPFoundation's Request, and then get specific input bags (query/request,...), the `get` may return `string|null`. However, if you pass parameter #2 `$default` as non-null value, it will never return `null`, and always a string.

So for example this code can never return null;

```
$request->query->get('name', 'default value');
```

Currently, because the typehint on the function is `string|null`, PHPStan will complain if you pass this to a function with a non-null argument, even though it will never return null;

```
Parameter #2 $name of class Foo constructor expects string, string|null given
```

This is tested on Symfony 5.1.

**Comment by raalderink** [comment]
I'll be working on a fix for this and will create a PR when ready

**Comment by ondrejmirtes** [comment]
This needs a dynamic return type extension https://phpstan.org/developing-extensions/dynamic-return-type-extensions :)

**Comment by ruudk** [comment]
Fixed in https://github.com/phpstan/phpstan-symfony/pull/107

Can be closed.
